// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Reto técnico INDRA",
    "version": "1"
  },
  "paths": {
    "/empresa": {
      "post": {
        "summary": "createEmpresa",
        "description": "",
        "operationId": "createEmpresa.post.empresa",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EmpresaReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/EmpresaRes"
            }
          }
        }
      },
      "get": {
        "summary": "getAllEmpresas",
        "description": "",
        "operationId": "getAllEmpresas.get.empresa",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Empresas"
            }
          }
        }
      }
    },
    "/empresa/{id}": {
      "get": {
        "summary": "getEmpresa",
        "description": "",
        "operationId": "getEmpresa.get.empresa/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/EmpresaRes"
            }
          }
        }
      }
    },
    "/vehicle/{id}": {
      "get": {
        "summary": "getVehiculo",
        "description": "",
        "operationId": "getVehiculo.get.vehicle/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/VehiculoRes"
            }
          }
        }
      }
    },
    "/vehicle": {
      "get": {
        "summary": "getAllVehiculos",
        "description": "",
        "operationId": "getAllVehiculos.get.vehicle",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Vehiculos"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Vehiculo": {
      "properties": {
        "nombre": {
          "title": "Vehiculo.nombre",
          "type": "string"
        },
        "modelo": {
          "title": "Vehiculo.modelo",
          "type": "string"
        },
        "fabricante": {
          "title": "Vehiculo.fabricante",
          "type": "string"
        },
        "costo_en_creditos": {
          "title": "Vehiculo.costo_en_creditos",
          "type": "string"
        },
        "longitud": {
          "title": "Vehiculo.longitud",
          "type": "string"
        },
        "velocidad_maxima": {
          "title": "Vehiculo.velocidad_maxima",
          "type": "string"
        },
        "tripulacion": {
          "title": "Vehiculo.tripulacion",
          "type": "string"
        },
        "pasajeros": {
          "title": "Vehiculo.pasajeros",
          "type": "string"
        },
        "capacidad_carga": {
          "title": "Vehiculo.capacidad_carga",
          "type": "string"
        },
        "consumidos": {
          "title": "Vehiculo.consumidos",
          "type": "string"
        },
        "clase_vehiculo": {
          "title": "Vehiculo.clase_vehiculo",
          "type": "string"
        },
        "pilotos": {
          "items": {
            "title": "Vehiculo.pilotos.[]",
            "type": "string"
          },
          "title": "Vehiculo.pilotos",
          "type": "array"
        },
        "peliculas": {
          "items": {
            "title": "Vehiculo.peliculas.[]",
            "type": "string"
          },
          "title": "Vehiculo.peliculas",
          "type": "array"
        },
        "creado": {
          "title": "Vehiculo.creado",
          "type": "string"
        },
        "editado": {
          "title": "Vehiculo.editado",
          "type": "string"
        },
        "url": {
          "title": "Vehiculo.url",
          "type": "string"
        }
      },
      "required": [
        "nombre",
        "modelo",
        "fabricante",
        "costo_en_creditos",
        "longitud",
        "velocidad_maxima",
        "tripulacion",
        "pasajeros",
        "capacidad_carga",
        "consumidos",
        "clase_vehiculo",
        "pilotos",
        "peliculas",
        "creado",
        "editado",
        "url"
      ],
      "additionalProperties": false,
      "title": "Vehiculo",
      "type": "object"
    },
    "VehiculoRes": {
      "properties": {
        "payload": {
          "properties": {
            "data": {
              "$ref": "#/definitions/Vehiculo",
              "title": "VehiculoRes.payload.data"
            }
          },
          "required": [
            "data"
          ],
          "additionalProperties": false,
          "title": "VehiculoRes.payload",
          "type": "object"
        }
      },
      "required": [
        "payload"
      ],
      "additionalProperties": false,
      "title": "VehiculoRes",
      "type": "object"
    },
    "Vehiculos": {
      "properties": {
        "payload": {
          "properties": {
            "data": {
              "items": {
                "$ref": "#/definitions/Vehiculo",
                "title": "Vehiculos.payload.data.[]"
              },
              "title": "Vehiculos.payload.data",
              "type": "array"
            }
          },
          "required": [
            "data"
          ],
          "additionalProperties": false,
          "title": "Vehiculos.payload",
          "type": "object"
        }
      },
      "required": [
        "payload"
      ],
      "additionalProperties": false,
      "title": "Vehiculos",
      "type": "object"
    },
    "Empresa": {
      "properties": {
        "razonSocial": {
          "title": "Empresa.razonSocial",
          "type": "string"
        },
        "direccion": {
          "title": "Empresa.direccion",
          "type": "string"
        },
        "telefono": {
          "title": "Empresa.telefono",
          "type": "string"
        },
        "ruc": {
          "title": "Empresa.ruc",
          "type": "string"
        }
      },
      "required": [
        "razonSocial",
        "direccion"
      ],
      "additionalProperties": false,
      "title": "Empresa",
      "type": "object"
    },
    "EmpresaReq": {
      "properties": {
        "payload": {
          "$ref": "#/definitions/Empresa",
          "title": "EmpresaReq.payload"
        }
      },
      "required": [
        "payload"
      ],
      "additionalProperties": false,
      "title": "EmpresaReq",
      "type": "object"
    },
    "EmpresaBody": {
      "properties": {
        "id": {
          "title": "EmpresaBody.id",
          "type": "string"
        },
        "razonSocial": {
          "title": "EmpresaBody.razonSocial",
          "type": "string"
        },
        "direccion": {
          "title": "EmpresaBody.direccion",
          "type": "string"
        },
        "telefono": {
          "title": "EmpresaBody.telefono",
          "type": "string"
        },
        "ruc": {
          "title": "EmpresaBody.ruc",
          "type": "string"
        }
      },
      "required": [
        "id",
        "razonSocial",
        "direccion"
      ],
      "additionalProperties": false,
      "title": "EmpresaBody",
      "type": "object"
    },
    "EmpresaRes": {
      "properties": {
        "payload": {
          "properties": {
            "data": {
              "$ref": "#/definitions/EmpresaBody",
              "title": "EmpresaRes.payload.data"
            }
          },
          "required": [
            "data"
          ],
          "additionalProperties": false,
          "title": "EmpresaRes.payload",
          "type": "object"
        }
      },
      "required": [
        "payload"
      ],
      "additionalProperties": false,
      "title": "EmpresaRes",
      "type": "object"
    },
    "Empresas": {
      "properties": {
        "payload": {
          "properties": {
            "data": {
              "items": {
                "$ref": "#/definitions/EmpresaBody",
                "title": "Empresas.payload.data.[]"
              },
              "title": "Empresas.payload.data",
              "type": "array"
            }
          },
          "required": [
            "data"
          ],
          "additionalProperties": false,
          "title": "Empresas.payload",
          "type": "object"
        }
      },
      "required": [
        "payload"
      ],
      "additionalProperties": false,
      "title": "Empresas",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};